version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: api-denuncias
    container_name: api-denuncias
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    depends_on:
      - redis
      - postgres
  redis:
    image: redis:latest
    container_name: api-denuncias-redis
    ports:
      - "6379:6379"
  postgres:
    image: postgres:latest
    container_name: api-denuncias-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
